name: Build and Release

on:
  workflow_dispatch:

jobs:

  # -----------------------------------------------------------------
  # TESTS
  # -----------------------------------------------------------------

  tests-cypress-modern:
    name: Run Tests (Playwright)
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Run all tests
      run: |
        echo "Installing dependencies..."
        yarn
        echo "Start Vite Preview..."
        yarn preview &>/dev/null &
        echo "Installing Playwright..."
        cd playwright
        npm ci
        npx playwright install --with-deps
        echo "Running tests..."
        npx playwright test -x
        
    - name: Upload Report
      uses: actions/upload-artifact@v3.0.0
      if: ${{ always() }}
      with:
        name: playwright-results
        path: playwright/test-results/
