name: Build and Release

on:
  workflow_dispatch:

jobs:

  # -----------------------------------------------------------------
  # TESTS
  # -----------------------------------------------------------------

  tests-playwright:
    name: Run Tests (Playwright)
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.25.2
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox]
        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        shardTotal: [10]
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Run all tests
      run: |
        echo "Installing dependencies..."
        yarn
        echo "Start Vite Preview..."
        yarn preview &>/dev/null &
        echo "Installing Playwright..."
        cd playwright
        npm ci
        echo "Running tests..."
        npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        
    - name: Upload Report
      uses: actions/upload-artifact@v3.0.0
      if: ${{ always() }}
      with:
        name: playwright-results-${{ matrix.project }}-${{ matrix.shardIndex }}-${{ matrix.shardTotal }}
        path: playwright/test-results/
